title: Remember_your_sisterhood
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "LittleSister"
  email: "miss.sonagi@gmail.com"
  url: "https://pinkrespect.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Little-Sister-Maisie"
year : "2020"
